# Generated by Django 3.1.11 on 2021-06-01 18:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_auto_20210528_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Text to display', requried=True))])), ('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Bold text for this card max length of 100 characters.', max_length=100, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image will be auto cropped to 570px by 370px.')), ('link', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='More Details', max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))], help_text='Enter a link or select a page'))])))])), ('image_and_text', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='will be cropped to 786x562px')), ('image_alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Image to the left'), ('right', 'Image to the right')], help_text='Image on the left with text on the right or Image on the right and text on the left')), ('title', wagtail.core.blocks.CharBlock(help_text=' max length is 60 characters', max_length=60)), ('text', wagtail.core.blocks.CharBlock(max_length=140, required=False)), ('link', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='More Details', max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))]))])), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='max length is 200 characters', max_length=200)), ('link', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(default='More Details', max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False))]))])), ('youtube', wagtail.core.blocks.StructBlock([('youtube_id', wagtail.core.blocks.CharBlock(help_text='youtube id here', max_length=30, required=True))])), ('spotify', wagtail.core.blocks.StructBlock([('artist_id', wagtail.core.blocks.CharBlock(help_text=' enter the artist id for spotify', max_length=30, required=True))])), ('richtext', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ol', 'ul', 'link'], template='streams/simple_richtext_block.html')), ('large_image', wagtail.images.blocks.ImageChooserBlock(help_text='This image will be cropped to 1200px by 775px', template='streams/large_image_block.html'))], blank=True, null=True),
        ),
    ]
