# Generated by Django 3.1.11 on 2021-06-02 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterCTASettings',
        ),
    ]
