# Generated by Django 3.1.11 on 2021-06-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('site_settings', '0002_delete_footerctasettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HoursSettings',
            new_name='LiveSettings',
        ),
    ]
